dependencies:
  - pip=9.0.1
  - python=3.6.1=2
  - h5py=2.7.0
  - pip:
    - keras==2.1.3
    - pipeline-runtime==1.0.6
    - nltk==3.4
    - pandas==0.24.1
    - requests==2.20.1
    - fuzzywuzzy==0.17.0
    - matplotlib==3.0.2
    - seaborn==0.9.0
    - numpy==1.16.1
    - spacy==2.1.3
    - tqdm==4.28.1
    - scikit_learn==0.20.3
